export const FETCHING_PRODUCT_LIST = 'FETCHING_PRODUCT_LIST';
export const FETCHING_PRODUCT_LIST_COMPLETE = 'FETCHING_PRODUCT_LIST_COMPLETE';
export const FETCHING_PRODUCT_LIST_FAILED = 'FETCHING_PRODUCT_LIST_FAILED';

export const FETCHING_FEATURED_PRODUCT = "FETCHING_FEATURED_PRODUCT";
export const FETCHING_FEATURED_PRODUCT_COMPLETE = 'FETCHING_FEATURED_PRODUCT_COMPLETE';
export const FETCHING_FEATURED_PRODUCT_FAILED = 'FETCHING_FEATURED_PRODUCT_FAILED';

export const PRODUCT_CATEGORY = "PRODUCT_CATEGORY";
